export const listData = [
  {
    name: "格付けくん",
    skills: "Vue.js, Golang",
    status: "active",
    complete: true,
    url: "https://kakutsuke-kun.com",
    image: "/images/services/rank_info.png",
    info: "フリーランス・個人の口コミサイトです。日頃の感謝や、仕事のお礼など、相手の評価につながる口コミを書くことが出来ます。",
  },
  {
    name: "Babel Bubble",
    skills: "React.js, Django",
    status: "active",
    complete: true,
    url: "https://babel-bubble.com",
    image: "/images/services/babel_info.png",
    info: "無料で遊べる投資シミュレーションゲームです。架空のアイテムをゲーム内通貨で売買して遊びます。",
  },
  {
    name: "人生は運ゲー",
    skills: "Wordpress",
    status: "active",
    complete: true,
    url: "https://monetizealchemist.com",
    image: "/images/services/monetizealchemist.png",
    info: "ブログです。お金をかけないで生きるサバイバル術を書いています。",
  },
  {
    name: "Props iOS",
    skills: "React-Native",
    status: "ios",
    complete: true,
    url: "https://itunes.apple.com/us/app/props-%E6%8C%81%E3%81%A1%E7%89%A9%E7%AE%A1%E7%90%86%E3%82%A2%E3%83%97%E3%83%AA/id1460285997?l=ja&ls=1&mt=8",
    image: "/images/services/props_info.png",
    info: "持ち物管理ができるiOSアプリです。自分の持ち物をアプリでまとめて管理できます。",
  },
  {
    name: "Props Android",
    skills: "React-Native",
    status: "android",
    complete: true,
    url: "https://play.google.com/store/apps/details?id=com.gitackt.props",
    image: "/images/services/props_info.png",
    info: "持ち物管理ができるAndroidアプリです。自分の持ち物をアプリでまとめて管理できます。",
  },
  {
    name: "VCU",
    skills: "Django",
    status: "deactive",
    complete: true,
    url: "https://v-cu.com",
    image: "/images/services/vcu_info.png",
    info: "仮想通貨のポートフォリオ管理サービスです。複数の取引所とAPI連携を行い自動でデータを取得します。",
  },
]