export const listData = [
  {
    name: "Babel Bubble",
    status: "active",
    complete: true,
    url: "https://babel-bubble.com",
    image: "/images/services/babelbubble.png",
    info: "無料で遊べる投資シミュレーションゲームです。架空のアイテムをゲーム内通貨で売買して遊びます。",
  },
  {
    name: "Props iOS",
    status: "ios",
    complete: true,
    url: "https://itunes.apple.com/us/app/props-%E6%8C%81%E3%81%A1%E7%89%A9%E7%AE%A1%E7%90%86%E3%82%A2%E3%83%97%E3%83%AA/id1460285997?l=ja&ls=1&mt=8",
    image: "/images/services/props.png",
    info: "持ち物管理ができるiOSアプリです。自分の持ち物をアプリでまとめて管理できます。",
  },
  {
    name: "Props Android",
    status: "android",
    complete: true,
    url: "https://play.google.com/store/apps/details?id=com.gitackt.props",
    image: "/images/services/props.png",
    info: "持ち物管理ができるAndroidアプリです。自分の持ち物をアプリでまとめて管理できます。",
  },
  {
    name: "暗号くん",
    status: "line",
    complete: true,
    url: "https://line.me/R/ti/p/%40hbi0385s",
    image: "/images/services/ango.png",
    info: "仮想通貨の情報を返してくれるLINE Botです。イーサリアムの情報をチャットで教えてくれます。",
  },
  {
    name: "人生は運ゲー",
    status: "active",
    complete: true,
    url: "https://monetizealchemist.com",
    image: "/images/services/monetizealchemist.png",
    info: "ブログです。お金をかけないで生きるサバイバル術を書いています。",
  },
  {
    name: "VCU",
    status: "active",
    complete: true,
    url: "https://v-cu.com",
    image: "/images/services/vcu.png",
    info: "仮想通貨のポートフォリオ管理サービスです。複数の取引所とAPI連携を行い自動でデータを取得します。",
  },
  {
    name: "Violet",
    status: "github",
    complete: true,
    url: "https://github.com/gitackt/violet",
    image: "/images/services/violet.png",
    info: "形態素解析とマルコフ連鎖で自動生成した文章をWordpressに自動投稿するシステムです。",
  },
  {
    name: "Freesia",
    status: "github",
    complete: true,
    url: "https://github.com/gitackt/freesia",
    image: "/images/services/freesia.png",
    info: "自動リライトシステムです。英語に翻訳した文章を再翻訳することで別の文章を自動生成します。",
  },
  {
    name: "Annabel",
    status: "github",
    complete: true,
    url: "https://github.com/gitackt/annabel",
    image: "/images/services/annabel.png",
    info: "複数のYouTube動画を同時に再生できるアプリケーションです。入力されたURLの動画を同時に再生します。",
  },
]