export const listData = [
  {
    name: "Babel Bubble",
    status: "active",
    complete: true,
    url: "https://babel-bubble.com",
    image: "/images/services/babelbubble.png",
    info: "バベルバブルは無料で遊べる投資シミュレーションゲームです。ゲーム内で流通するアイテムをゲーム内通貨で売買して遊びます。",
  },
  {
    name: "VCU",
    status: "active",
    complete: true,
    url: "https://v-cu.com",
    image: "/images/services/vcu.png",
    info: "VCUは複数の取引所から自動でデータを取得して仮想通貨のポートフォリオを簡単にチェックすることができるサービスです。",
  },
  {
    name: "暗号くん",
    status: "line",
    complete: true,
    url: "https://line.me/R/ti/p/%40hbi0385s",
    image: "/images/services/ango.png",
    info: "暗号くんはブロックチェーンから仮想通貨の情報を返してくれるLINE Botです。アドレス残高やGas相場などの情報をチャットで教えてくれます。",
  },
  {
    name: "Props iOS",
    status: "ios",
    complete: false,
    url: "https://babel-bubble.com",
    image: "/images/services/props.png",
    info: "Propsは持ち物管理ができるiOSアプリです。自分の持ち物をアプリでまとめて管理できます。Propsで管理すれば物をなくしません。",
  },
  {
    name: "Props Android",
    status: "android",
    complete: false,
    url: "https://babel-bubble.com",
    image: "/images/services/props.png",
    info: "Propsは持ち物管理ができるAndroidアプリです。自分の持ち物をアプリでまとめて管理できます。Propsで管理すれば物をなくしません。",
  },
  {
    name: "Freesia",
    status: "github",
    complete: true,
    url: "https://github.com/gitackt/freesia",
    image: "/images/services/freesia.png",
    info: "フリージアは自動リライトシステムです。元の文章を英語に翻訳し、再翻訳することで同じ意味を持つ別の文章を自動生成します。",
  },
  {
    name: "Annabel",
    status: "github",
    complete: true,
    url: "https://github.com/gitackt/annabel",
    image: "/images/services/annabel.png",
    info: "アナベルは複数のYouTube動画を同時に再生できるアプリケーションです。入力されたの動画のURLを検出し、すべてのビデオを表示します。",
  },
  {
    name: "人生は運ゲー",
    status: "active",
    complete: true,
    url: "https://monetizealchemist.com",
    image: "/images/services/monetizealchemist.png",
    info: "ブログです。",
  },
]